from pathlib import Path

from ida_util import FunctionStatus, get_status_from_color, get_repo_root

def getNameToPath():
    mapping = {}
    tree = ida_dirtree.get_std_dirtree(ida_dirtree.DIRTREE_FUNCS)
    class treeTraversal(ida_dirtree.dirtree_visitor_t):
        def visit(self, cursor, direntry):
            if direntry.isdir:
                return 0

            mapping[tree.get_entry_name(direntry)] = tree.get_abspath(cursor)
            return 0
            
    tree.traverse(treeTraversal())
    return mapping

# https://github.com/josephH00/ida-InTooDeep/blob/639258049e8033a939320d9371f961e83db6dfad/InTooDeep.py#L67-L84
def getFuncAbsPath(ea):
    tree = ida_dirtree.get_std_dirtree(ida_dirtree.DIRTREE_FUNCS)
    funcName = ida_funcs.get_func_name(ea)

    absPath = ""

    class treeTraversal(ida_dirtree.dirtree_visitor_t):
        def visit(self, cursor, direntry):
            if direntry.isdir or funcName != tree.get_entry_name(direntry):
                return 0

            nonlocal absPath
            absPath = tree.get_abspath(cursor)

            return -1

    tree.traverse(treeTraversal())
    return absPath

def is_autogenerated(name: str) -> bool:
    if name.startswith("sub_"):
        return True
    if name.startswith("nullsub_"):
        return True
    if name.startswith("j_"):
        return True
    return False

with open(get_repo_root() / "data" / "file_list.yml", "w", newline='\n') as f:
    try:
        ida_kernwin.show_wait_box("Exporting")
        name2path = getNameToPath()
        text_segm = ida_segment.get_segm_by_name(".text")
        
        last_folder = None
        for i in range(ida_funcs.get_func_qty()):
            if ida_kernwin.user_cancelled():
                break
            if i % 3456 == 0:
                ida_kernwin.replace_wait_box("Exporting; function %d/%d" % (i+1, ida_funcs.get_func_qty()))

            func = ida_funcs.getn_func(i)
            if func.start_ea < text_segm.start_ea or func.start_ea >= text_segm.end_ea:
                continue  # skip functions outside of .text (e.g. .plt stubs)

            offset = func.start_ea
            size = func.end_ea - func.start_ea
            label = ida_name.get_name(offset)
            status = get_status_from_color(RGB_BGR(ida_funcs.get_func(offset).color)).name
            folder = name2path[label]

            if is_autogenerated(label):
                label="''"
            
            folder = folder.rsplit("/", 1)[0].strip("/")
            if not folder:
                folder = "UNKNOWN"
            
            if folder != last_folder:
                f.write(f"{folder}:\n")
                f.write(f"  '.text':\n")
                last_folder = folder
            
            f.write(f"  - offset: 0x{(offset - 0x7100000000):06x}\n")
            f.write(f"    size: {size}\n")
            f.write(f"    label: {label}\n")
            f.write(f"    status: {status}\n")
    finally:
        ida_kernwin.hide_wait_box()
